# Additionally, you may want to set the following property if your travis build fails with “rakefile not found” by adding to the top of your .travis.yml file:
# language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t veraloq/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true veraloq/react-test npm test

after_success:
  # build production version of all the component of the project
  - docker build -t veraloq/fib-calc-client ./client
  - docker build -t veraloq/fib-calc-nginx ./nginx
  - docker build -t veraloq/fib-calc-server ./server
  - docker build -t veraloq/fib-calc-worker ./worker

  # push them to the Docker Hub
