# Additionally, you may want to set the following property if your travis build fails with “rakefile not found” by adding to the top of your .travis.yml file:
# language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t mkawski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mkawski/react-test npm test

after_success:
  # Build production version of all the component of the project.
  - docker build -t mkawski/fib-calc-client ./client
  - docker build -t mkawski/fib-calc-nginx ./nginx
  - docker build -t mkawski/fib-calc-server ./server
  - docker build -t mkawski/fib-calc-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take these images and push them to Docker Hub.
  - docker push mkawski/fib-calc-client
  - docker push mkawski/fib-calc-nginx
  - docker push mkawski/fib-calc-server
  - docker push mkawski/fib-calc-worker

deploy:
  # provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'fibonacci-calculator'
  env: 'Fibonaccicalculator-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-343270885324'
  bucket_path: 'fibonacci-calculator'
  # on:
  #   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
