version: '3'
services:
  client:
    image: 'mkawski/fib-calc-client'
    mem_limit: 128m
    hostname: client
  server:
    image: 'mkawski/fib-calc-server'
    mem_limit: 128m
    hostname: api # We renamed it to api because server is a keyword in nginx.
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'mkawski/fib-calc-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'mkawski/fib-calc-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
